{% set name = "djangocms-style" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms-style-{{ version }}.tar.gz
  sha256: 2f28dfc299615b51b57cdc92ccdd3db1aba706d42d7038335b25f893fabfa1c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django-cms >=3.7
    - djangocms-attributes-field >=1

test:
  imports:
    - djangocms_style
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-cms/djangocms-style
  summary: Adds style plugin to django CMS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
